config/routes.rb
Hsdraft::Application.routes.draw do

  root 'welcome#index'

  resources :drafts
  get 'cards' => 'cards#index'

end

app/models/card.rb
class Card < ActiveRecord::Base

  validates :type, inclusion: { in: %w(minion spell weapon),
            message: "%{value} is not a valid card type" }

  # in the future, don't name a column 'type'
  self.inheritance_column = nil

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  #TODO: get this working after adding User model
  belongs_to :user
end

app/models/draft.rb
class Draft < ActiveRecord::Base
  has_many :selections
  has_many :comments

  belongs_to :hero
end

app/models/hero.rb
class Hero < ActiveRecord::Base
end

app/models/selection.rb
class Selection < ActiveRecord::Base
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  respond_to :json

  def index
    @cards = Card.all
  end

end

app/controllers/drafts_controller.rb
class DraftsController < ApplicationController

  def new
    @draft = Draft.new
  end

  def create
    @draft = Draft.new(draft_params)

    redirect_to draft_path(@draft) if @draft.save
  end

  def show
    @draft = Draft.find params[:id]
  end

  private

    def draft_params
      params.require(:draft).permit(:hero_id)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/drafts_helper.rb
module DraftsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/drafts/new.html.haml
%div(class='container')
  = form_for @draft, html: { class: 'form-inline' } do |f|
    = f.select :hero_id, Hero.all.map { |hero| [hero.name, hero.id] }, {}, { class: "form-control" }
    = f.submit(class: "btn btn-primary")

app/views/drafts/show.html.haml
%div(id="content")
  %div(class="container")
    %input{type: "text", class: "typeahead", id: "card-search", data: { hero: @draft.hero_id} }
  %div(class="container")
    %div(id="set" class="row-fluid")

app/views/layouts/_header.html.haml
%nav(class="navbar navbar-default navbar-fixed-top" role="navigation")
  %div(class="container")
    %div(class="navbar-header")
      = link_to "Hearthstone Draft", root_path, class: "navbar-brand"

app/views/layouts/application.html.haml
!!! 5
%html{ :lang => 'en' }
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1")
    %title= "Hsdraft"
    = stylesheet_link_tag     "application"
    = stylesheet_link_tag     "http://static-hearth.cursecdn.com/current/skins/Hearth/css/tooltip.css"
    = javascript_include_tag  "application"
    = javascript_include_tag  "http://static-hearth.cursecdn.com/current/js/syndication/tt.js"
    = csrf_meta_tags
    /[if lt IE 9]
      %script(src="http://html5shiv.googlecode.com/svn/trunk/html5.js")
  %body
    = render "layouts/header"
    = yield

app/views/welcome/index.html.haml
%div(class='container')
  %div(class='col-md-2 col-md-offset-5')
    = button_to "Get Started", new_draft_path, { :method => :get, class: 'btn btn-primary btn-lg' }